[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 30

[env]
PHP_VERSION = "8.3"
NIXPACKS_PHP_EXTRA_EXTS = "mysqli pdo_mysql"
